name: regala_e3dady
description: Regala e3dady - A Flutter application.

# The following line prevents the package from being accidentally published to pub.dev using pub publish.
# This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Add the firebase_core and firebase_auth packages
  firebase_auth: ^5.6.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.1
  webview_flutter: ^4.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  path_provider: ^2.0.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  url_launcher_web: ^2.0.5
  intl: 0.20.2
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  vibration: ^3.1.3
  whatsapp_unilink: ^2.1.0
  firebase_messaging: ^15.0.4
  html: ^0.15.4
  cached_network_image: ^3.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.4
  fl_chart: ^1.0.0
  confetti: ^0.7.0
  cloud_functions: ^5.5.2
  package_info_plus: ^8.0.2
  file_saver: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/SAINT_GEORGRE.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  image_path: "assets/SAINT_GEORGRE.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img.png
    - assets/st_george.png
    - assets/img_1.png
    - assets/cross.png
    - assets/logo_el_group.png
    - assets/regala_e3dady.png
    - assets/sky_background.jpg
    - assets/crosses_bg.png
    - assets/SAINT_GEORGRE.png
      

